### ISSUE TITLE
8 deployments with incorrect or no date

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camera-trap-datasets#1]
The following deployments have no incorrect date info

- [x] 26a3e3dd-2650-47c4-8951-8c9b34ebe5e9: PUNT_39 `+01:00`
- [x] 41b8d770-d91a-4896-9db5-46477bb6aa20: PUNT_27 `+01:00`
- [x] 4b20da2b-ffdd-49a3-beed-c2561b02aa3a: JW_0363 `50024-04-30T23:16:40+01:00`
- [x] 5af98261-5a34-458f-84dd-2bc23cef4bc0: JW_0737 x2 `+01:00`
- [x] 5ded7b5b-ff3e-472b-a890-3a661490f930: JW_0364 `50016-07-14T01:16:40+01:00`
- [x] 706a10c2-fd9a-436f-8021-50a1a1682b84: JW_0362 `50024-07-28T03:23:20+01:00`
- [x] a2663720-e182-4ac7-8e35-e3745b706101: JW_0365 `50024-05-29T20:53:20+01:00`
- [x] dc2e43b4-6dd3-4c8c-b6d4-f21abb746ef1: JW_0361 `50024-08-18T21:53:20+01:00`

They should either be removed (when no media/obs attached) or their date corrected.

**Comment by milotictanja** [comment]
I deleted 26a3e3dd-2650-47c4-8951-8c9b34ebe5e9 (empty), and corrected 706a10c2-fd9a-436f-8021-50a1a1682b84 and dc2e43b4-6dd3-4c8c-b6d4-f21abb746ef1 (correct dates).
The other deployments in the list should be deleted as well, but they contain set-up images. I asked Yorick to delete those (I don't think I can remove multimedia).

**Comment by milotictanja** [comment]
All incorrect deployments in the list are deleted.
