### ISSUE TITLE
14 observations without timestamp (empty sequences)

### ISSUE THREAD

**Issue by peterdesmet** [inbo/camera-trap-datasets#2]
The following observations do not have any timestamp info (just `+01:00`): [observations_no_timestamp.csv](https://github.com/inbo/camera-trap-datasets/files/9504351/observations_no_timestamp.csv). All of them are marked as `unclassified`. The missing date is typically the result of sequences that were created without images. Those sequences should be removed.

- [x] ab1f25e7-9493-4dfe-9e72-16641a6b7fd3:seq
- [x] c4062541-00ca-45e7-8cd0-c22c7b749554:seq
- [x] 8cc32179-fc7a-434b-9ae7-b81e41805021:seq
- [x] dd3747f1-665e-4540-903f-94e855bd16d8:seq
- [x] 8a31c77f-aee8-4a24-bbc6-78fc7ae46ef8:seq
- [x] b7b03a4f-8ee0-4731-84e9-c6a073ca93b4:seq
- [x] 516c079d-d6c6-40fd-847b-bb26d75194dd:seq
- [x] 33b38bcc-ca35-4905-88da-91ed411189c3:seq
- [x] dc3d3f36-7ae1-46fd-bfa3-88b8b4462691:seq
- [x] 98864799-6e5d-4011-9457-79ab70f04af9:seq
- [x] 818a88c6-e244-40be-995e-459ec86c3f9c:seq
- [x] 987d7c62-7143-43da-a899-94d704e80481:seq
- [x] 24ccac67-0a05-49c4-bc92-de3f862d9393:seq
- [x] 8d09c391-6bc3-448a-b5ec-1da48ff38a84:seq

**Comment by milotictanja** [comment]
All sequences in the list are indeed empty. I asked Yorick to remove those because I don't think I can remove sequences directly in Agouti.

**Comment by milotictanja** [comment]
Loose sequences can't be deleted, but I labeled the empty observations as blank in Agouti. That should allow us to filter out these observations when publishing the data.

**Comment by peterdesmet** [comment]
Yorick should be able to delete empty sequences in the database

**Comment by peterdesmet** [comment]
This issue seems resolved.
