### ISSUE TITLE
Wrong locations

### ISSUE THREAD

**Issue by milotictanja** [inbo/camera-trap-datasets#4]
The following locations have coordinates far from National Park Hoge Kempen (Northern France or South-West Germany):

- [x] MISTAKE (Latitude 48.6908333333, Longitude 5.14055555556)
- [x] MISTAKE (Latitude 48.6908333333, Longitude 9.14055555556)
- [x] NPHK000 (Latitude 48.6908333333, Longitude 9.14055555556)
- [x] NPHK00 (Latitude 48.6908333333, Longitude 9.14055555556)
- [ ] NPHK0 (Latitude 48.6908333333, Longitude 9.14055555556)

1 deployment + set-up images is linked to NPHK0 (no observations, only set-up). There are no deployments, observations or images linked to the other locations in the list.

**Comment by milotictanja** [comment]
@peterdesmet OK to delete those locations?

**Comment by peterdesmet** [comment]
Yes, ok to remove unused (and incorrect) locations and the 1 associated deployment.

**Comment by milotictanja** [comment]
OK, done
